# TODO: Make this into a read-only txt file and not a script

derogatory = ["cock-up",
              "wanker",
              "twat",
              "bell-end",
              "tosser",
              "idiot",
              "muppet",
              "slag",
              "dolt",
              "right proper mess",
              "minx",
              "arse",
              "doo-doo head",
              "daft bastard",
              "churl",
              "chode",
              "nimrod",
              "scalawag",
              "twit",
              "sausage",
              "cretin",
              "will-duh-beast",
              "bitch",
              "coward",
              "varlet",
              "curr",
              "ass-hat",
              "pirate",
              "bollock",
              "milksop",
              "asswipe",
              "dick",
              "dolt",
              'donkey',
              'gimp',
              'harlot',
              'bed-wetter'
              ]
